# vim:ft=kitty

## name:     base24 Melange Light
## author:   savq (base24 adaptation by alexander)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-kitty
## blurb:    

# Scheme name: base24 Melange Light
# Scheme author: savq (base24 adaptation by alexander)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-kitty)

# The basic colors
background #f1f1f1
foreground #54433a
selection_background #54433a
selection_foreground #f1f1f1

# Cursor colors
cursor #54433a
cursor_text_color #f1f1f1

# URL underline color when hovering with mouse
url_color #7d6658

# Kitty window border colors
active_border_color #a98a78
inactive_border_color #e9e1db

# OS Window titlebar colors
wayland_titlebar_color #f1f1f1
macos_titlebar_color #f1f1f1

# Tab bar colors
active_tab_background #f1f1f1
active_tab_foreground #54433a
inactive_tab_background #e9e1db
inactive_tab_foreground #7d6658
tab_bar_background #e9e1db

# The 16 terminal colors
# normal
color0 #f1f1f1
color1 #bf0021
color2 #3a684a
color3 #a06d00
color4 #465aa4
color5 #904180
color6 #3d6568
color7 #54433a

# bright
color8 #d9d3ce
color9 #c77b8b
color10 #6e9b72
color11 #bc5c00
color12 #7892bd
color13 #be79bb
color14 #739797
color15 #2c211a

# extended base16 colors
color16 #bc5c00
color17 #7d6658
color18 #e9e1db
color19 #d9d3ce
color20 #7d6658
color21 #433229
