#!/bin/sh
# Tinty hook: generate foot theme from base24 palette
# Writes both [colors-dark] and [colors-light] with the same palette
# so foot works regardless of system color-scheme preference.

hex() {
  eval "printf '%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

BG=$(hex 00)
FG=$(hex 05)
SEL_FG=$(hex 00)
SEL_BG=$(hex 0D)

R0=$(hex 05) R1=$(hex 12) R2=$(hex 14) R3=$(hex 09)
R4=$(hex 16) R5=$(hex 17) R6=$(hex 15) R7=$(hex 03)
B0=$(hex 04) B1=$(hex 08) B2=$(hex 0B) B3=$(hex 0A)
B4=$(hex 0D) B5=$(hex 0E) B6=$(hex 0C) B7=$(hex 02)

OUT="$HOME/.config/foot/themes/tinted.ini"

write_section() {
  cat << EOF
[$1]
alpha=1.0
background=${BG}
foreground=${FG}

selection-foreground=${SEL_FG}
selection-background=${SEL_BG}

regular0=${R0}
regular1=${R1}
regular2=${R2}
regular3=${R3}
regular4=${R4}
regular5=${R5}
regular6=${R6}
regular7=${R7}

bright0=${B0}
bright1=${B1}
bright2=${B2}
bright3=${B3}
bright4=${B4}
bright5=${B5}
bright6=${B6}
bright7=${B7}
EOF
}

{
  echo "# Auto-generated by tinty — do not edit"
  echo ""
  write_section "colors-dark"
  echo ""
  write_section "colors-light"
} > "$OUT"
