#!/bin/sh
# Tinty hook: generate hyprland theme from base24 palette

hex() {
  eval "printf '%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

BLUE=$(hex 0D)
GREEN=$(hex 0B)
UI=$(hex 03)
FG=$(hex 05)
OUT="$HOME/.config/hypr/themes/current.conf"

cat > "$OUT" << HYPR
# Auto-generated by tinty — do not edit
general:col.active_border   = rgba(${BLUE}ee) rgba(${GREEN}ee) 45deg
general:col.inactive_border = rgba(${UI}aa)
decoration:shadow:color = rgba(${FG}55)
HYPR
