#!/bin/sh
# Tinty hook: generate hyprland theme from base24 palette

hex() {
  eval "printf '%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

BLUE=$(hex 0D)
GREEN=$(hex 0B)
UI=$(hex 03)
FG=$(hex 05)
OUT="$HOME/.config/hypr/themes/current.lua"

cat > "$OUT" << HYPR
-- Auto-generated by tinty — do not edit
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba(${BLUE}ee)", "rgba(${GREEN}ee)" }, angle = 45 },
            inactive_border = "rgba(${UI}aa)",
        },
    },
    decoration = {
        shadow = { color = "rgba(${FG}55)" },
    },
})
HYPR

# Also refresh the legacy hyprlang theme, so renaming hyprland.lua away still
# falls back to a correctly-themed hyprland.conf. Drop this once .conf is gone.
cat > "$HOME/.config/hypr/themes/current.conf" << HYPR
# Auto-generated by tinty — do not edit
general:col.active_border   = rgba(${BLUE}ee) rgba(${GREEN}ee) 45deg
general:col.inactive_border = rgba(${UI}aa)
decoration:shadow:color = rgba(${FG}55)
HYPR
