#!/bin/sh
# Tinty hook: generate sway theme from base24 palette

hex() {
  eval "printf '#%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

BG=$(hex 00)
FLOAT=$(hex 01)
UI=$(hex 03)
FG=$(hex 05)
BLUE=$(hex 0D)
RED=$(hex 08)

OUT="$HOME/.config/sway/90-theme.conf"

cat > "$OUT" << SWAY
# Auto-generated by tinty — do not edit
font \$font
client.focused          ${BLUE} ${BLUE} ${BG} ${BLUE} ${BLUE}
client.focused_inactive ${UI} ${FLOAT} ${FG} ${FLOAT} ${FLOAT}
client.unfocused        ${FLOAT} ${FLOAT} ${UI} ${FLOAT} ${FLOAT}
client.urgent           ${RED} ${RED} ${BG} ${RED} ${RED}
SWAY
