#!/bin/sh
# Tinty hook: generate tmux theme from base24 palette

hex() {
  eval "printf '#%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

BG=$(hex 00)
FLOAT=$(hex 01)
SEL=$(hex 02)
UI=$(hex 03)
COM=$(hex 04)
FG=$(hex 05)
RED=$(hex 08)
GREEN=$(hex 0B)
BLUE=$(hex 0D)

OUT="$HOME/.config/tmux/themes/current.conf"

cat > "$OUT" << TMUX
# Auto-generated by tinty — do not edit

# Status bar
set -g status-style                 "bg=${FLOAT},fg=${FG}"
set -g status-left-style            "bg=${FLOAT},fg=${FG}"
set -g status-right-style           "bg=${FLOAT},fg=${FG}"
set -g status-left-length           60
set -g status-right-length          60

set -g status-left  ' #[bold,fg=${RED}]<3 #[nobold,fg=${GREEN}]#S #[fg=${UI}]| '
set -g status-right '#[fg=${UI}]| #[fg=${FG},bold]%H:%M #[nobold,fg=${COM}]· %d %b %Y '

# Windows
set -g window-status-separator " "
set -g window-status-format         "#[fg=${COM},bg=${FLOAT}] #{s/0/⁰/;s/1/¹/;s/2/²/;s/3/³/;s/4/⁴/;s/5/⁵/;s/6/⁶/;s/7/⁷/;s/8/⁸/;s/9/⁹/:window_index} #W#{?window_zoomed_flag, 🔍,⁕} "
set -g window-status-current-format "#[fg=${BG},bg=${BLUE},bold] #{s/0/⁰/;s/1/¹/;s/2/²/;s/3/³/;s/4/⁴/;s/5/⁵/;s/6/⁶/;s/7/⁷/;s/8/⁸/;s/9/⁹/:window_index} #W#{?window_zoomed_flag, 🔍,⁕} "
set -g window-status-activity-style "fg=${RED},bg=${FLOAT}"
set -g window-status-bell-style     "fg=${RED},bg=${FLOAT},bold"

# Panes
set -g pane-border-style        "fg=${UI}"
set -g pane-active-border-style "fg=${BLUE}"

# Dim inactive panes
set -g window-style        "bg=${FLOAT},fg=${FG}"
set -g window-active-style "bg=${BG},fg=${FG}"

# Messages
set -g message-style         "bg=${SEL},fg=${FG}"
set -g message-command-style "bg=${SEL},fg=${FG}"

# Copy mode (use colour indices — hex needs RGB terminal capability)
set -g mode-style "bg=colour67,fg=colour255,bold"

# Clock
set -g clock-mode-colour "${BLUE}"
TMUX
