#!/bin/sh
# Tinty hook: generate waybar CSS variables from base24 palette

hex() {
  eval "printf '#%s%s%s' \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_R\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_G\" \"\$TINTY_SCHEME_PALETTE_BASE${1}_HEX_B\""
}

OUT="$HOME/.config/waybar/themes/tinted.css"

cat > "$OUT" << CSS
/* Auto-generated by tinty — do not edit */
@define-color mel-bg     $(hex 00);
@define-color mel-float  $(hex 01);
@define-color mel-sel    $(hex 02);
@define-color mel-ui     $(hex 03);
@define-color mel-com    $(hex 04);
@define-color mel-fg     $(hex 05);

@define-color mel-red     $(hex 08);
@define-color mel-yellow  $(hex 0A);
@define-color mel-green   $(hex 0B);
@define-color mel-cyan    $(hex 0C);
@define-color mel-blue    $(hex 0D);
@define-color mel-magenta $(hex 0E);

@define-color mel-red-mute     $(hex 12);
@define-color mel-yellow-mute  $(hex 13);
@define-color mel-green-mute   $(hex 14);
@define-color mel-blue-mute    $(hex 16);
CSS
