# Melange (light) — savq/melange-nvim palette
# https://github.com/savq/melange-nvim

[main]
font=MonoLisa:size=13
prompt="❯ "
layer=overlay
lines=12
width=45
horizontal-pad=12
vertical-pad=8
inner-pad=4

[colors]
background=F1F1F1ff
text=54433Aff
match=465AA4ff
selection=D9D3CEff
selection-text=54433Aff
selection-match=465AA4ff
border=A98A78ff
counter=7D6658ff

[border]
width=2
radius=8
