require('plugin-configs.saga')
require('plugin-configs.telescope')
require('plugin-configs.treesitter')
require('plugin-configs.completion')
require('plugin-configs.spellsitter')
require('plugin-configs.nvimtree')
