#!/bin/env bash

# rbw config set email "alexanderlhc@disroot.org"
# rbw config set base_url "https://api.bitwarden.eu"
# rbw config set identity_url "https://identity.bitwarden.eu"

# examples showing the result:
# example.com	
# example2.com	Folder
# list=$(rbw list --fields name,folder | sed 's/&/\&amp;/g')
list=$(rbw list --fields name,folder | sed 's/&/\&amp;/g')

selected_row=$(echo "$list" | ~/.config/wofi/wofi_launch.sh --dmenu)

# item=$(echo "$selected_row" | awk '{print $1}')
item=$(echo "$selected_row" | awk -F'\t' '{print $1}')

echo "$item"

password=$(rbw get "$item")

wl-copy "$password"

sleep 6

cliphist delete-query "$password"

# vim: filetype=bash
