# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ config --unset branch.master.remote
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ config --unset branch.master.merge
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ config branch.master.remote origin
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ config branch.master.merge refs/heads/master

# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ remote remove origin
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ remote add origin [your-repository-url]
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ fetch
# git --git-dir=/home/alexander/.local/share/dotfiles/ --work-tree=/home/alexander/ branch --set-upstream-to=origin/master master
