-- Auto-generated by tinty — do not edit
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba(465aa4ee)", "rgba(3a684aee)" }, angle = 45 },
            inactive_border = "rgba(a98a78aa)",
        },
    },
    decoration = {
        shadow = { color = "rgba(54433a55)" },
    },
})
