#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

#exec-once = wl-paste --watch cliphist store
pgrep -x "wl-paste" >/dev/null && pkill -x "wl-paste"
wl-paste --watch cliphist store &

# nm-applet
pgrep -x "nm-applet" >/dev/null && pkill -x "nm-applet"
nm-applet &

run_polkit_agent "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"

uwsm app -- waybar
