general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid multiple instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action="on"})'  # avoid needing a second keypress to wake
}

# Lock after 10 min idle
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Screens off after 15 min idle
listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action="off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}
