#! /bin/sh

sh ~/.config/bspwm/autolaunch.sh
sh ~/.config/bspwm/monitors.sh

setxkbmap dk
#~/.config/bspwm/gnome-keyring

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# fixes gray java windows
wmname LG3D

# vi: ft=bash
