#! /bin/sh

# autolaunch
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x picom > /dev/null || picom &
pgrep -x greenclip > /dev/null || greenclip daemon &
pgrep -x nextcloud > /dev/null || nextcloud &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location.lat, .location.lng' | tr '\n' ':' | sed 's/:$//') &

hsetroot -cover ~/.local/share/nextcloud/wallpapers/IMG_20200502_151338.jpg

setxkbmap dk
~/.config/bspwm/gnome-keyring
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# fixes gray java windows
wmname LG3D
