#!/usr/bin/env bash

endpoint="https://api.github.com/notifications"
user="AlexanderLHC"
header="Accept: application/vnd.github.v3+json"
key="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"

notifications=$(curl -sf -u $user:$key -H $header $endpoint | jq length)

echo $notifications
