#!/usr/bin/env bash

endpoint="https://api.github.com/notifications"
user="AlexanderLHC"
header="Accept: application/vnd.github.v3+json"
key=$(cat ~/.local/share/access.token)

notifications=$(curl -sf -u $user:$key -H $header $endpoint | jq length)

echo "$key" 

echo "$notifications"
